### ISSUE TITLE
I am facing following on fast typing, fast autocomplete...

### ISSUE THREAD

**Issue by kumail-raza** [doomtrooper/GoogleAutoCompleteWithRecyclerView#1]
Can you provide solution for this issue : 

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.unation.app, PID: 26549
                                                                 java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 5(offset:5).state:6
                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4368)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4326)
                                                                     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1955)
                                                                     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1364)
                                                                     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1327)
                                                                     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:556)
                                                                     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2713)
                                                                     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3011)
                                                                     at android.view.View.layout(View.java:15671)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                                                                     at android.view.View.layout(View.java:15671)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                                                                     at android.view.View.layout(View.java:15671)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                     at android.view.View.layout(View.java:15671)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                     at android.view.View.layout(View.java:15671)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                     at android.view.View.layout(View.java:15671)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                     at android.view.View.layout(View.java:15671)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                     at android.view.View.layout(View.java:15671)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by doomtrooper** [comment]
could not reproduce the error...will try again
